# File cấu hình chính (Entry point) của Docker Compose
# Sử dụng tính năng 'include' để gộp các file cấu hình con, giúp quản lý dễ dàng hơn.
include:
  - docker-compose.infra.yml # Cấu hình hạ tầng (Database, Redis, MinIO) - BẮT BUỘC
  - docker-compose.core.yml # Cấu hình lõi OpenVidu/LiveKit Server - BẮT BUỘC
  - docker-compose.apps.yml # Các ứng dụng đi kèm (Dashboard, App Meet mẫu) - TÙY CHỌN
  - docker-compose.streaming.yml # Streaming & Recording (Egress/Ingress) - TÙY CHỌN (Nặng)

# Định nghĩa mạng chung cho toàn bộ các container trong dự án này kết nối với nhau
networks:
  default:
    name: openvidu-community
